"""Initial database schema

Revision ID: d9b14e47cac0
Revises: 
Create Date: 2025-11-09 00:29:07.328323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b14e47cac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('added_by', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('street', 'house_number', name='uix_street_house')
    )
    op.create_index(op.f('ix_addresses_queue_id'), 'addresses', ['queue_id'], unique=False)
    op.create_index(op.f('ix_addresses_street'), 'addresses', ['street'], unique=False)
    op.create_table('crowdreports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowdreports_queue_id'), 'crowdreports', ['queue_id'], unique=False)
    op.create_index(op.f('ix_crowdreports_reported_at'), 'crowdreports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_crowdreports_status'), 'crowdreports', ['status'], unique=False)
    op.create_index(op.f('ix_crowdreports_user_id'), 'crowdreports', ['user_id'], unique=False)
    op.create_table('iot_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('is_power_on', sa.Boolean(), nullable=False),
    sa.Column('voltage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iot_data_received_at'), 'iot_data', ['received_at'], unique=False)
    op.create_index(op.f('ix_iot_data_sensor_id'), 'iot_data', ['sensor_id'], unique=False)
    op.create_table('iot_sensors',
    sa.Column('sensor_id', sa.String(length=50), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('sim_card', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    op.create_index(op.f('ix_iot_sensors_queue_id'), 'iot_sensors', ['queue_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_sent_at'), 'notifications', ['sent_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('subscription_days', sa.Integer(), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('queues',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_power_on', sa.Boolean(), nullable=True),
    sa.Column('last_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_change_source', sa.String(length=20), nullable=True),
    sa.Column('total_outages', sa.Integer(), nullable=True),
    sa.Column('total_uptime_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('referral_activations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referred_user_id', sa.BigInteger(), nullable=False),
    sa.Column('days_granted', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_index(op.f('ix_referral_activations_referrer_user_id'), 'referral_activations', ['referrer_user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_queue_id'), 'schedules', ['queue_id'], unique=False)
    op.create_index(op.f('ix_schedules_scheduled_date'), 'schedules', ['scheduled_date'], unique=False)
    op.create_table('user_addresses',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'address_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_channel_subscribed', sa.Boolean(), nullable=True),
    sa.Column('last_subscription_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_address_id', sa.Integer(), nullable=True),
    sa.Column('address_count', sa.Integer(), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('referral_days_earned', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('total_notifications_sent', sa.Integer(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_is_channel_subscribed'), 'users', ['is_channel_subscribed'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_referred_by'), 'users', ['referred_by'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_referred_by'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_is_channel_subscribed'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_schedules_scheduled_date'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_queue_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_referral_activations_referrer_user_id'), table_name='referral_activations')
    op.drop_table('referral_activations')
    op.drop_table('queues')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sent_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_iot_sensors_queue_id'), table_name='iot_sensors')
    op.drop_table('iot_sensors')
    op.drop_index(op.f('ix_iot_data_sensor_id'), table_name='iot_data')
    op.drop_index(op.f('ix_iot_data_received_at'), table_name='iot_data')
    op.drop_table('iot_data')
    op.drop_index(op.f('ix_crowdreports_user_id'), table_name='crowdreports')
    op.drop_index(op.f('ix_crowdreports_status'), table_name='crowdreports')
    op.drop_index(op.f('ix_crowdreports_reported_at'), table_name='crowdreports')
    op.drop_index(op.f('ix_crowdreports_queue_id'), table_name='crowdreports')
    op.drop_table('crowdreports')
    op.drop_index(op.f('ix_addresses_street'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_queue_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
